### ISSUE TITLE
Issue of parallel running

### ISSUE THREAD

**Issue by Jarvis-K** [oxwhirl/comix#2]
I am trying to reproduce the experiment results on particle and MAMujoco, however the `batch size_run = 1` makes it expensive with respect to time. For example, the predator and prey may need $33$ hours to finish the training and the MAMujoco need much more. 
So I am wondering whether there exists the parallel config that can reproduce the result in your paper? If there is, would u like to share it for an efficient reproducing?

**Comment by beipeng** [comment]
Hi, very sorry for the late reply! Yes, it is quite annoying that using batch_size_run=1 makes things very slow. It is very slow to train on MAMuJoCo now. You can train it less frequently to speed it up, but that is likely to affect the learning performance significantly. I'm working on implementing RNN version for things and using the episode runner instead, but it's still under development.
