### ISSUE TITLE
the mujoco_key.txt in docker

### ISSUE THREAD

**Issue by yeshenpy** [oxwhirl/comix#4]
when I run config the docker, I get this problem ,

Step 42/47 : RUN python3 -c "import mujoco_py"
 ---> Running in e5f0fa38b0a2
ERROR: Invalid activation key

I use the mjkey.txt for the command:  COPY ./mujoco_key.txt .mujoco/mjkey.txt

Is there a solution?

**Comment by beipeng** [comment]
Hi, thanks for raising the issue! You need a MuJoCo license activation key in order to install it. I'm assuming you already have one. But you should name your file mujoco_key.txt (but not mjkey.txt) based on this command, and put it under pymarl-dev/.  Hope that solves your problem!
