### ISSUE TITLE
Copy mjkey.txt failed

### ISSUE THREAD

**Issue by chauncygu** [oxwhirl/comix#5]
Step 35/47 : COPY ./mujoco_key.txt .mujoco/mjkey.txt
COPY failed: stat /var/lib/docker/tmp/docker-builder252510345/mujoco_key.txt: no such file or directory

**Comment by beipeng** [comment]
Hi, thanks for raising the issue! You need a MuJoCo license activation key in order to install it. I had to remove the mujoco_key.txt file that contains the license activation key since I can't release that. Hope that solves your problem!
