### ISSUE TITLE
ERROR: Invalid activation key  Press Enter to exit ...The command '/bin/sh -c python3 -c "import mujoco_py"' returned a non-zero code: 1

### ISSUE THREAD

**Issue by chauncygu** [oxwhirl/comix#6]
Step 35/47 : COPY ./mujoco_key.txt .mujoco/mjkey.txt
COPY failed: stat /var/lib/docker/tmp/docker-builder252510345/mujoco_key.txt: no such file or directory

I have install mujoco_py, and it can work in my virtual environment, but when I run the bash build.sh, it arises the above problem,
how do you solve the problem?

**Comment by beipeng** [comment]
Hi, thanks for raising the issue! I put a file named mujoco_key.txt (under pymarl-dev/) that contains the MuJoCo license activation key in order to install it (but I can't release that). Hope that solves your problem!
