### ISSUE TITLE
'GenericDict' object has no attribute 'scenario_name'

### ISSUE THREAD

**Issue by chauncygu** [oxwhirl/comix#8]

**Comment by at-peter** [comment]
I am also encountering this error when I am trying to run the main.py file. Is there any quick workaround?

**Comment by pengzhenghao** [comment]
Just look into the source code and change all `scenario_name ` to `scenario`

**Comment by beipeng** [comment]
Thanks for raising and fixing the issue guys! I just pushed a small fix.
